FROM jupyterhub/jupyterhub:5

RUN pip install --no-cache-dir \
    jupyterhub-nativeauthenticator \
    jupyterlab \
    notebook \
    openai \
    requests \
    pandas \
    numpy \
    matplotlib \
    seaborn \
    ipywidgets
